server:
  port: 8888

spring:
  application:
    name: gateway-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: QQ@13837730156
    url: jdbc:mysql://sh-cdb-4wtef0js.sql.tencentcdb.com:60308/nyrmt?serverTimezone=Asia/Shanghai
    hikari:
      max-lifetime: 50000
  jpa:
    generate-ddl: true
    show-sql: true
  redis:
    host: 192.168.21.128
    password: lagelangri

zuul:
  routes:
    token:
      url: http://127.0.0.1:7777
    order:
      url: http://127.0.0.1:8081
  sensitive-headers:

  ratelimit:
    enabled: true
    repository: REDIS
    default-policy-list:
      - limit: 2 #请求数 100
        quota: 1 #100个请求不超过5秒
        refresh-interval: 3 #60秒只能有100个请求
        type:
          - url
          - httpmethod